[package]
name = "zaeon_pro_card"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
# Usando o repositório oficial da Movement Labs
git = "https://github.com/movementlabsxyz/aptos-framework.git"
rev = "main" # Para o Hackathon M1, a branch main da Movement é a correta
subdir = "aptos-framework"

[dependencies.AptosTokenObjects]
# Mesma fonte para garantir que os objetos de NFT (DAS) sejam compatíveis
git = "https://github.com/movementlabsxyz/aptos-framework.git"
rev = "main"
subdir = "aptos-token-objects"

[addresses]
zaeon_addr = "0xf86d857123ebeb3dabaf45bd46b788beefc852fff8f02add2acf61f2bb17862e"